[platformio]
default_envs = seeed_xiao_esp32s3

[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
upload_speed = 115200

; XIAO S3 Standard has 8MB Flash, No PSRAM
board_build.partitions = default_8MB.csv
board_upload.flash_size = 8MB
board_build.flash_mode = qio

lib_deps =
    zinggjm/GxEPD2 @ ^1.5.0
    mathertel/OneButton @ ^2.0.3
    bblanchon/ArduinoJson @ ^6.21.3
    esphome/ESPAsyncWebServer-esphome @ ^3.1.0
    esphome/AsyncTCP-esphome @ ^2.0.0
    tzapu/WiFiManager @ ^2.0.17
    bitbank2/unzipLIB @ ^1.0.0
    https://github.com/bitbank2/PNGdec.git
    https://github.com/bitbank2/JPEGDEC.git
    https://github.com/bitbank2/bb_epaper.git
    https://github.com/thijse/Arduino-Log.git

build_flags =
    -D BOARD_SEEED_XIAO_ESP32S3
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D CORE_DEBUG_LEVEL=3
    -I include

board_build.filesystem = littlefs
